# Generated by Django 4.2.6 on 2023-10-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
